POST http://localhost:5174/api/workout
Content-Type: application/json

{
  "workoutTypeId": "c0165cc8-a981-4166-8ce8-26bc97e84667",
  "location": "Knoxville, TN",
  "distance": "3.2",
  "steps": 1000,
  "calories": 200,
  "notes": "evening walk"
}

