GET http://localhost:5173/emailconfirm/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM4MjY5ODQ2LTI4MzItNDhkYi05NTZmLTZhOTQ0MjYyYTAwZiIsImVtYWlsIjoicm9iLm1vbmRheUBvdXRsb29rLmNvbSIsImZpcnN0TmFtZSI6IlJvYiBBIiwibGFzdE5hbWUiOiJNb25kYXkiLCJlbWFpbENvbmZpcm1lZCI6ZmFsc2UsImlhdCI6MTY4MjUyODQyMiwiZXhwIjoxNjgyNjE0ODIyfQ.hMOBx4ktFjMav6LwsNPLDGskl1kjQn7fnwVBzbkT0oM
Content-Type: application/json