GET http://localhost:5174/api/workout/feed
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzNDM1ZjUzLWEyMmUtNDFiMC1iZmE3LWE2ZDIxYmFjODRmNyIsImVtYWlsIjoicm9iLm1vbmRheUBvdXRsb29rLmNvbSIsImlhdCI6MTY4MDg5MDk2MH0.3xOzX8Fmd1SXQz8XimV-qrvRq-rECPCD_6stblxQxsw