POST http://localhost:5174/user/login
Content-Type: application/json

{
  "email": "jennie.marie.rhodes@gmail.com",
  "password": "password"
}

###
POST http://localhost:5174/user/login
Content-Type: application/json

{
  "email": "rmonday@clemson.edu",
  "password": "High17!"
}